import xhsi_data
# Controls & annunciators
SIM_COCKPIT2_ANNUNCIATORS_MASTER_CAUTION = 350
SIM_COCKPIT2_ANNUNCIATORS_MASTER_WARNING = 351
SIM_COCKPIT2_CONTROLS_GEAR_HANDLE_DOWN = 352
SIM_COCKPIT2_ANNUNCIATORS_GEAR_UNSAFE = 353
XHSI_AIRCRAFT_GEAR_COUNT = 354 # Calculated from sim/aircraft/parts/acf_gear_type int[10]
SIM_COCKPIT2_CONTROLS_PARKING_BRAKE_RATIO = 355
SIM_COCKPIT_LIGHTS = 356 # bit-fields: taxi_light_on/strobe_lights_on/nav_lights_on/landing_lights_on/beacon_lights_on
SIM_COCKPIT2_CONTROLS_FLAP_RATIO = 358 # this is supposed to be the handle location
SIM_COCKPIT2_CONTROLS_FLAP_HANDLE_DEPLOY_RATIO = 357 # this is supposed to be the indicator
SIM_AIRCRAFT_CONTROLS_ACF_FLAP_DETENTS = 359
SIM_COCKPIT2_ANNUNCIATORS_AUTOPILOT_DISCONNECT = 360
SIM_COCKPIT2_ANNUNCIATORS_FUEL_QUANTITY = 361
SIM_COCKPIT2_ANNUNCIATORS_GPWS = 362
SIM_COCKPIT2_ANNUNCIATORS_ICE = 363
SIM_COCKPIT2_ANNUNCIATORS_PITOT_HEAT = 364
SIM_COCKPIT2_ANNUNCIATORS_STALL_WARNING = 365
SIM_COCKPIT2_ANNUNCIATORS_GEAR_WARNING = 366
SIM_COCKPIT2_SWITCHES_AUTO_BRAKE_LEVEL = 367
SIM_COCKPIT2_CONTROLS_SPEEDBRAKE_RATIO = 368
SIM_FLIGHTMODEL2_CONTROLS_SPEEDBRAKE_RATIO = 369
SIM_FLIGHTMODEL2_GEAR_DEPLOY_RATIO_ = 370 # array of 10 floats
XHSI_AIRCRAFT_GEAR_DOOR_DEPLOY_RATIO_ = 380 # array of 10 floats
SIM_COCKPIT2_CONTROLS_YOKE_PITCH_RATIO = 390
SIM_COCKPIT2_CONTROLS_YOKE_ROLL_RATIO = 391
SIM_COCKPIT2_CONTROLS_YOKE_HDG_RATIO = 396
SIM_COCKPIT2_CONTROLS_ELEVATOR_TRIM = 392
SIM_COCKPIT2_CONTROLS_AILERON_TRIM = 393
SIM_COCKPIT2_CONTROLS_RUDDER_TRIM = 394
SIM_FLIGHTMODEL_CONTROLS_SLATRAT = 395
SIM_COCKPIT2_CONTROLS_LEFT_BRK_RATIO = 397
SIM_COCKPIT2_CONTROLS_RIGHT_BRK_RATIO = 398
XHSI_AIRCRAFT_GEAR_DOOR_COUNT = 399 # Calculated from sim/aircraft/gear/acf_gear_door_type int[20]


# Control surface positions : rudder, elevators, ailerons, spoilers
SIM_FLIGHTMODEL_CONTROLS_RUDDER = 650
SIM_FLIGHTMODEL_CONTROLS_LEFT_ELEV = 651
SIM_FLIGHTMODEL_CONTROLS_RIGHT_ELEV = 652
SIM_FLIGHTMODEL_CONTROLS_LEFT_AIL = 653
SIM_FLIGHTMODEL_CONTROLS_RIGHT_AIL = 654

id = {
    'SIM_COCKPIT2_CONTROLS_YOKE_PITCH_RATIO':390,
    'SIM_COCKPIT2_CONTROLS_YOKE_ROLL_RATIO':391,
    'SIM_COCKPIT2_CONTROLS_YOKE_HDG_RATIO':396,
    'SIM_COCKPIT2_CONTROLS_ELEVATOR_TRIM':392,
    'SIM_COCKPIT2_CONTROLS_AILERON_TRIM':393,
    'SIM_COCKPIT2_CONTROLS_RUDDER_TRIM':394,
    'SIM_FLIGHTMODEL_CONTROLS_SLATRAT':395,
    'SIM_COCKPIT2_CONTROLS_LEFT_BRK_RATIO':397,
    'SIM_COCKPIT2_CONTROLS_RIGHT_BRK_RATIO':398
    }


def setflightcontrol(id,v):
    
    if id==SIM_COCKPIT2_CONTROLS_FLAP_RATIO:
        xhsi_data.fc['leftflap'] = v * 40
        xhsi_data.fc['rightflap'] = v * 40
    elif id==SIM_COCKPIT2_CONTROLS_ELEVATOR_TRIM:
        xhsi_data.fc['stabtrim'] = v * 10
    elif id==SIM_COCKPIT2_CONTROLS_AILERON_TRIM:
        xhsi_data.fc['ailtrim'] = v * 10
    elif id==SIM_COCKPIT2_CONTROLS_RUDDER_TRIM:
        xhsi_data.fc['ruddertrim'] = v * 10

    elif id==SIM_FLIGHTMODEL2_CONTROLS_SPEEDBRAKE_RATIO:
        xhsi_data.fc['spoilersAll'] = v

    elif id==SIM_FLIGHTMODEL_CONTROLS_RUDDER:
        xhsi_data.fc['rudder'] = v
    elif id==SIM_FLIGHTMODEL_CONTROLS_LEFT_ELEV:
        xhsi_data.fc['left_elev'] = v
    elif id==SIM_FLIGHTMODEL_CONTROLS_RIGHT_ELEV:
        xhsi_data.fc['right_elev'] = v 
    elif id==SIM_FLIGHTMODEL_CONTROLS_LEFT_AIL:
        xhsi_data.fc['left_ail'] = v
    elif id==SIM_FLIGHTMODEL_CONTROLS_RIGHT_AIL:
        xhsi_data.fc['right_ail'] = v

if __name__ == "__main__":
    setflightcontrol(650,0)
    
        
